
version: '3'
volumes:
  postgres_data: {}
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - migration
      - db
  migration:
    build:
      context: .
      dockerfile: migration.Dockerfile
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres
    environment:
      POSTGRES_USER: rpg
      POSTGRES_PASSWORD: game
      POSTGRES_DB: rpggame
    volumes:
      - postgres_data:/var/lib/postgresql/data