const STRINGS = {
  BATTLE_HEADER_MSG: 'You are challenged to a battle!',
  BATTLE_CHARACTER_NAME_MSG: 'Character name',
  BATTLE_CONTAINER_HEADER_MSG: 'Choose a course of action',
  BATTLE_LEVEL_MSG: 'Level ',
  BATTLE_STAT_MSG: 'Stat',
  BATTLE_VALUE_MSG: 'Value',
  BATTLE_HEALTH_STAT_MSG: 'Health',
  BATTLE_ATTACK_STAT_MSG: 'Attack',
  BATTLE_DEFENSE_STAT_MSG: 'Defense',
  BATTLE_MAGIC_ATTACK_STAT_MSG: 'Magic Attack',
  BATTLE_MAGIC_DEFENSE_STAT_MSG: 'Magic Defense',
  BATTLE_LOG_CONTAINER_HEADER_MSG: 'Battle Log',
  BATTLE_BUTTON_ATTACK: 'Attack',
  BATTLE_BUTTON_MAGIC: 'Magic Attack',
  BATTLE_BUTTON_INVENTORY: 'Inventory',
  BATTLE_BUTTON_ESCAPE: 'Run Away',
  BATTLE_SELECT_NPC_MODAL_HEADER_MSG: 'Select the NPC you wish to battle',
  BATTLE_SELECT_NPC_MODAL_SELECT_BUTTON_MSG: 'Battle',
  BATTLE_SELECT_NPC_MODAL_NO_NPCS_MSG: 'NPCs unavailable',
  BATTLE_RESULT_MODAL_HEADER_ESCAPE_MSG: 'You successfully escaped from the ',
  BATTLE_RESULT_MODAL_HEADER_LOSS_MSG: 'You were defeated by the ',
  BATTLE_RESULT_MODAL_HEADER_WIN_MSG: 'You defeated the ',
  BATTLE_RESULT_MODAL_BODY_MSG: 'Click below to continue your adventure',
  BATTLE_RESULT_MODAL_FOOTER_HOME_BTN: 'Take me Home'
};

const NUMBERS = {
  BATTLE_ESCAPE_SUCCESS_1: 1,
  BATTLE_DAMAGE_0: 0,
  BATTLE_ATTACK_TYPE_0: 0,
  BATTLE_HEALTH_MULTIPLIER: 100,
  BATTLE_NPC_ATTACK_TIMEOUT_VAL: 1000
};

export {
  STRINGS,
  NUMBERS
}
